# Generated by Django 2.0.7 on 2019-02-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that mail already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
