language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
services: # => 3
  - mysql
env: # => 4
  - DJANGO=2.0.7 DB=mysql
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test