language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
services: # => 3
  - mysql
env: # => 4
  - DJANGO=2.0.7 DB=mysql
install:
  - pip install -r requirements.txt
before_script: # => 6
  - mysql -e 'create database test;' -u root  
# command to run tests
script:
  - python manage.py test